trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  serviceConnection: 'myservcon'
  workingDirectory: 'terraform'

steps:

- checkout: self

- task: AzureCLI@2
  displayName: 'Terraform Deployment'
  inputs:
    azureSubscription: '$(serviceConnection)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    workingDirectory: '$(workingDirectory)'
    inlineScript: |

      echo "========== Azure Login =========="
      az account show

      echo "========== Install Terraform =========="
      TERRAFORM_VERSION=1.8.5

      wget https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip

      unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip

      sudo mv terraform /usr/local/bin/

      terraform version

      echo "========== Terraform Init =========="

      terraform init

      echo "========== Terraform Validate =========="

      terraform validate

      echo "========== Terraform Plan =========="

      terraform plan

      echo "========== Terraform Apply =========="

      terraform apply -auto-approve